# Generated by Django 3.0.4 on 2020-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200408_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_states',
            field=models.CharField(blank=True, max_length=9999),
        ),
    ]
